[package]
name = "sql-console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#const-concat = "0.1.0"
const_format = "0.2.23"
rpassword = "6.0.1"
mysql = "22.1.0"